apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-deployment
  labels:
    app: front-vue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front-vue
  template:
    metadata:
      labels:
        app: front-vue
    spec:
      containers:
        - name: front-vue
          image: ziedmeddeb123/front-vue:v1.0
          ports:
            - containerPort: 5173

---

apiVersion: v1
kind: Service
metadata:
  name: vue-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: front-vue
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
      nodePort: 30001
