apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  serviceName: zookeeper
  replicas: 3
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      hostname: "zookeeper"
      subdomain: "zookeeper"
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.0.1
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
            - name: ZOOKEEPER_INIT_LIMIT
              value: "5"
            - name: ZOOKEEPER_SYNC_LIMIT
              value: "2"
            - name: ZOOKEEPER_SERVERS
              value: "zookeeper-0.zookeeper:2888:3888;zookeeper-1.zookeeper:2888:3888;zookeeper-2.zookeeper:2888:3888"
          command:
            - sh
            - -c
            - |
              export ZOOKEEPER_SERVER_ID=$((`hostname | awk -F '-' '{print $2}'` + 1))
              echo $ZOOKEEPER_SERVER_ID > /var/lib/zookeeper/data/myid
              exec /etc/confluent/docker/run
          ports:
            - containerPort: 2181
              name: client
            - containerPort: 2888
              name: server
            - containerPort: 3888
              name: leader-election
          volumeMounts:
            - name: data
              mountPath: /var/lib/zookeeper/data
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  clusterIP: None
  ports:
    - name: client
      port: 2181
      protocol: TCP
  selector:
    app: zookeeper